### PR TITLE
[WIP] feat: add linux platform support [flatpak single file]

### PR DESCRIPTION
**Pull request by lil5**
As you can see from this Github Action [lil5 5108248692](https://github.com/lil5/isar/runs/5108248692?check_suite_focus=true), the building works.

> **Note:** I did encounter this bug https://github.com/svenstaro/upload-release-action/issues/57 which seems to be a network load issue on Github's side, the fix for now is to just re-run the action

### CODE REVIEW

**Comment by lil5** [comment]
I'm running the action once more and testing the result to see if it works from a different machine

**Comment by leisim** [comment]
Let me know when I can merge it :)

**Comment by JsonLinesCode** [comment]
Any update ?

**Comment by lil5** [comment]
You have see from my fork the hell I've gone through to try and get it to build using GitHub Actions. 

@JsonLinesCode If you want you can checkout my AppImage branch and build it yourself. Beware of trying to run the same on GitHub Actions, you have been warned. 

In terms of trying to build Flatpaks I was almost there, I still need to change it so that the build is moved to `/app` and a symlink is created from `/app/bin/isar` to `/app/isar`. 

This sent on mobile so I might not get it perfect

**Comment by leisim** [comment]
This is obsolete with the new inspector

**Pull request closed without merging**
