### PR TITLE
lint improvements

### PR DESCRIPTION
**Pull request by h1376h**
Hey! Thanks a lot for Hive and Isar.

This PR includes some improvements, all suggested by dart's default lint.

Most of these changes are made by running `dart fix --apply`, after setting analyzer temporarily to `strong-mode`. No breaking changes and no changes in behavior.

### CODE REVIEW

**Comment by leisim** [comment]
Hey, thanks for this PR! Could you please rebase it? I think many of those lints are already fixed now :)

**Comment by h1376h** [comment]
After rebasing, none of the changes were needed, keep it up! Thanks for updating Isar and sorry for the other unrelated PR.

**Comment by leisim** [comment]
Sorry for not being able to use the PR 😕

**Comment by h1376h** [comment]
Will make another one soon. :)

**Pull request closed without merging**
