### PR TITLE
Update quickstart.md

### PR DESCRIPTION
**Pull request by Bohne13**
Screenshot from 2023-12-30 16-17-15
Removed the separate line for running the builder tools with 'flutter pub run'. 
It looks like this is deprecated and replaced by only run 'dart run build_runner build'

### CODE REVIEW

**Comment by nobkd** [comment]
You could also change the other languages with this PR. What do you think?

- https://github.com/isar/isar/blob/main/docs/docs/tutorials/quickstart.md?plain=1#L49-L53
- https://github.com/isar/isar/blob/main/docs/docs/es/tutorials/quickstart.md?plain=1#L47-L51
- https://github.com/isar/isar/blob/main/docs/docs/fr/tutorials/quickstart.md?plain=1#L47-L51
- https://github.com/isar/isar/blob/main/docs/docs/it/tutorials/quickstart.md?plain=1#L47-L51
- https://github.com/isar/isar/blob/main/docs/docs/ja/tutorials/quickstart.md?plain=1#L48-L52
- https://github.com/isar/isar/blob/main/docs/docs/ko/tutorials/quickstart.md?plain=1#L47-L51
- https://github.com/isar/isar/blob/main/docs/docs/pt/tutorials/quickstart.md?plain=1#L47-L51
- https://github.com/isar/isar/blob/main/docs/docs/ur/tutorials/quickstart.md?plain=1#L44-L48
- https://github.com/isar/isar/blob/main/docs/docs/zh/tutorials/quickstart.md?plain=1#L47-L51

**Comment by Bohne13** [comment]
> You could also change the other languages with this PR. What do you think?
> 
> * https://github.com/isar/isar/blob/main/docs/docs/tutorials/quickstart.md?plain=1#L49-L53
> * https://github.com/isar/isar/blob/main/docs/docs/es/tutorials/quickstart.md?plain=1#L47-L51
> * https://github.com/isar/isar/blob/main/docs/docs/fr/tutorials/quickstart.md?plain=1#L47-L51
> * https://github.com/isar/isar/blob/main/docs/docs/it/tutorials/quickstart.md?plain=1#L47-L51
> * https://github.com/isar/isar/blob/main/docs/docs/ja/tutorials/quickstart.md?plain=1#L48-L52
> * https://github.com/isar/isar/blob/main/docs/docs/ko/tutorials/quickstart.md?plain=1#L47-L51
> * https://github.com/isar/isar/blob/main/docs/docs/pt/tutorials/quickstart.md?plain=1#L47-L51
> * https://github.com/isar/isar/blob/main/docs/docs/ur/tutorials/quickstart.md?plain=1#L44-L48
> * https://github.com/isar/isar/blob/main/docs/docs/zh/tutorials/quickstart.md?plain=1#L47-L51

I try to ASAP at first I have to figuring out if and How to add this commits to this PR. Would be better dann crating for each language a single PR.

**Comment by nobkd** [comment]
I just assume, that you are new to git and GitHub:

If you're okay with doing one commit for each file, you can change it from GitHub's web interface.
Go to [your fork of Isar](https://github.com/Bohne13/isar), change to the branch you used to open the PR, in your case thatÄs [`patch-1`](https://github.com/Bohne13/isar/tree/patch-1), go to the files, click on edit, remove the specific lines, commit the change for the file.

If you have `git` installed on your computer, you can do it all in one commit:
clone the forked repository `git clone ...` (https vs ssh cloning), switch to the pr branch: `git switch patch-1` from within the project folder, edit all the files, commit the changes: `git commit -am "your commit message"` and push to GitHub: `git push`

Feel free to ask / ping, if you need further advice.

**Comment by Bohne13** [comment]
Should be all languages.
For the 'it' file I'm not 100% sure that it worked out as I thought.

**Review by Aturex1 — APPROVED** [review]

**Pull request closed without merging**
