### PR TITLE
docs: add Chinese translation

### PR DESCRIPTION
**Pull request by ritksm**
[skip ci]

### CODE REVIEW

**Comment by leisim** [comment]
That's so cool @ritksm. Most important language after English. Thanks!!! Please let me know when you're ready :)

**Comment by ritksm** [comment]
> 

sure, might take a few days to finish

**Comment by lodisy** [comment]
Hello not seen this, but I have fully finished the Chinese translations. Shall I pull a request or? @leisim @ritksm

**Comment by ritksm** [comment]
> That's so cool @ritksm. Most important language after English. Thanks!!! Please let me know when you're ready :)

translation done, and rebased @leisim

**Comment by ritksm** [comment]
> Hello not seen this, but I have fully finished the Chinese translations. Shall I pull a request or? @leisim @ritksm

what a coincidence😄

**Comment by ritksm** [comment]
also, a new file `.original_commit` added to track upstream changes

**Comment by ritksm** [comment]
> @ritksm @lodisy I'm a bit unsure how to proceed here. Which translation should we merge? Are they the same? I'll add both of you as contributors of course

Both translations are complete and the content is basically the same, only some expressions are different.
I'm ok with either PR being merged😁 up to you to decide @leisim

**Comment by lodisy** [comment]
> @ritksm @lodisy I'm a bit unsure how to proceed here. Which translation should we merge? Are they the same? I'll add both of you as contributors of course

I am fine with either too. It's just different styles. Some parts of mine is closer to free translation instead of verbatim translation. 

But after either being merged, we might still need to do a bit polish here and there. ;)

**Comment by leisim** [comment]
@all-contributors please add @ritksm for translation.

**Comment by leisim** [comment]
I merged the other translation as it contained additional fixes for other languages. Thanks to both of you for your awesome work!!

**Pull request closed without merging**
