### PR TITLE
Make links work based on IDs

### PR DESCRIPTION
**Pull request by shroff**
Possible implementation of #598

### CODE REVIEW

**Comment by shroff** [comment]
@leisim I'm not sure if this is the direction you want to go with, but I thought I'd throw something together that works well with existing APIs, and works as expected with IDs.

**Comment by leisim** [comment]
It's a good start but I don't like the fact that it will break some of the other link methods if you add an object by id. I'd rather just have an `updateIds()` method that does not affect the link state.

**Comment by shroff** [comment]
I'm happy to do that, but I'm curious what this breaks. From my understanding (and tests), things work as expected. It's just that when you set `valueId`, the `value` gets reset and thus must be loaded again. Any `updateIds` method would have to do the same to avoid inconsistency, no?

**Comment by jakobhec** [comment]
@leisim thanks for your great work! Is there any update on this?

**Comment by simc** [comment]
Thanks for this PR. I'm going to close it however since it's obsolete for v4

**Pull request closed without merging**
