### PR TITLE
[Isar] Change the type all of `Isar.minId`, `Isar.maxId`, `Isar.autoIncrement` to `Id`

### LINKED ISSUE #495: Using `Isar.autoIncrement` may result in the error "No id property defined. Use the "Id" type for your id property".
**Steps to Reproduce**

1. Edit scheme.dart.
    ```dart
    import 'package:isar/isar.dart';
    
    part 'scheme.g.dart';
    
    @Collection()
    class Test {
      final id = Isar.autoIncrement;
    }
    ```
2. When run `flutter pub run build_runner build`, an error message is displayed.
    ```shell
    No id property defined. Use the "Id" type for your id property.
    package:demo/scheme.dart:6:7
      ╷
    6 │ class Test {
      │       ^^^^^^^^
      ╵
    ```

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 3.0.5
 - Isar version: 3.0.0-dev.7
 - Isar Generator version: 3.0.0-dev.7

**Cause**

- The type of `Isar.autoIncrement` is `int`.
    https://github.com/isar/isar/blob/0661c6b958be786ccb3eb0653e1f7ad52acf2ccc/packages/isar/lib/src/isar.dart#L36
- If `type.alias?.element.name` is `Id`, it is converted to `IsarType.id`, and if `IsarType.id` can't be found, an error occurs.
    https://github.com/isar/isar/blob/0661c6b958be786ccb3eb0653e1f7ad52acf2ccc/packages/isar_generator/lib/src/isar_type.dart#L179-L184    https://github.com/isar/isar/blob/0661c6b958be786ccb3eb0653e1f7ad52acf2ccc/packages/isar_generator/lib/src/isar_analyzer.dart#L76-L82

**Solution**

Change the type of `Isar.autoIncrement` to `Id`.

```diff
-  static int autoIncrement = isarAutoIncrementId;
+  static Id autoIncrement = isarAutoIncrementId;
```

### PR DESCRIPTION
**Pull request by blendthink**
## Issue

Fixes #495

## Future plans

If you like, I will add the test code to `isar_generator` after release.

image

### CODE REVIEW

**Review by leisim — APPROVED** [review]

**Comment by leisim** [comment]
Thanks for this PR. What do you mean by "test code for isar_generator"?

**Comment by leisim** [comment]
@all-contributors please add @blendthink for maintenance.

**Comment by blendthink** [comment]
@leisim 
Thanks for the review and for adding me as a contributor!

> What do you mean by "test code for isar_generator"?

Currently, the `isar_generator` package only has test code for errors, so I'm thinking of adding test code for successes like this one.

**Comment by leisim** [comment]
If you find a way to verify generator output that would be really cool!

**Pull request merged**
