### PR TITLE
Removed unnecessary todo, Added final keyword

### PR DESCRIPTION
**Pull request by Abhishek01039**
Removed unnecessary todo
Added final keyword
Added const keyword to one constructor

### CODE REVIEW

**Comment by leisim** [comment]
Thanks 👍😊

**Comment by Abhishek01039** [comment]
Hello @leisim 
image

Here should we remove `??=` and just put `=`
Thanks.

**Comment by leisim** [comment]
@Abhishek01039 this code is generated by ffigen. I cannot change it manually.

I think the reason for this assignment is to only lookup functions once.

**Comment by Abhishek01039** [comment]
Yeah ok Thanks

**Comment by leisim** [comment]
@Abhishek01039 I'll add a very basic example when I release Isar (hopefully today or tomorrow). If you want to create an example, I could link it in the docs. Did you get Isar to run?

**Comment by Abhishek01039** [comment]
Not yet @leisim

**Pull request merged**
