### PR TITLE
Init mono_repo

### PR DESCRIPTION
**Pull request by listepo**
Install [mono_repo](https://github.com/google/mono_repo.dart)
Quick setup the project locally `mono_repo pub get`

`packages/isar_flutter_libs/example/.gitkeep` temporary fix for https://github.com/flutter/flutter/issues/75644

@leisim what do you think of using `mono_repo`?

### CODE REVIEW

**Comment by leisim** [comment]
@listepo What are the advantages of `mono_repo`? It would be nice if we could automate the publishing process. Is that possible?

**Comment by listepo** [comment]
@leisim everything that is available at the moment:
Available commands:

-   `check`       Check the state of the repository.
-   `generate`    Generates the CI configuration for child packages.
-   `presubmit`   Run the CI presubmits locally.
-   `pub`         Run `pub get` or `pub upgrade` against all packages.
-   `travis`      (Deprecated, use `generate`) Configure Travis-CI for child packages.

most useful for local development `mono_repo pub get` and `mono_repo pub upgrade`
> It would be nice if we could automate the publishing process. Is that possible?

unfortunately not at the moment https://github.com/google/mono_repo.dart/issues/14

**Comment by Jjagg** [comment]
@leisim I currently have an automated publishing step set up with GitHub Actions for a package I maintain. It auto publishes when the version of a package is higher than the version on pub.dev and adds a tag to the Git repo. It does not take dependencies into account (yet), so you can't publish multiple packages in one run if one depends on the other. (I don't publish multiple packages yet, so I didn't need to fix this yet, but I think there's an easy fix: limit parallel runs to 1 and define packages in the build matrix in the right order.)

There's a manual step involved to copy your pub.dev credentials to a GitHub secret. IIRC you can find them at .pub-cache/credentials.json after authenticating to pub.dev from the CLI.

https://github.com/Jjagg/boustro/blob/main/.github/workflows/publish.yml

**Comment by leisim** [comment]
@Jjagg sounds interesting I'll definitely try it out. Thanks 😊

**Comment by listepo** [comment]
@leisim what do you think about https://docs.page/invertase/melos/automated-releases#publishing?

**Comment by leisim** [comment]
@listepo Wow this looks perfect 😍

**Pull request closed without merging**
